### ISSUE TITLE
Apraxis depends on pixels_against_humanity

### ISSUE THREAD

**Issue by christianromney** [apraxis/apraxis#8]
The file `resources/templates/component_jig.html` has an embedded dependency to the Pixels project that we'll want to break:

```
<script src="/js/pixels_against_humanity_client.js"></script>
```

The file `src/cljs/apraxis/client/jig.cljs` also depends on Pixels.

**Comment by aredington** [comment]
Resolved with 416db87c11d54de0e2eebc8d136ffcb22b02841d
